### ISSUE TITLE
Find solution to download on midnight details  of movies from TMDb

### ISSUE THREAD

**Issue by noemiko** [magdaprzybylska/top-movies#4]
Read about potential solutions how download every day data from TMDB
AC:
- compare potential solutions
- update change log

**Comment by magdaprzybylska** [comment]
Cron tab vs Advanced Python Scheduler 

1. the plan is to use a scheduler to call the API on e.g. midnight every day, get its data and put it inside the database 
2. this database would be updated daily 
3. instead of calling API every time, I will use my own copy to get the results 
4. as far as I could research, the Cron tab will probably suit the program’s needs best: 
- it’s easy to set up and use
- has a good documentation 
- has a special version for the Flask application 
- I’ve been looking for experienced programmers’ opinions and most of them recommended the cron tab over AP Scheduler, which leads me to believe that it has a bigger community, hence in case of errors, it will be easier to find solutions

**Comment by noemiko** [comment]
Great you can make ADR from your research https://github.com/joelparkerhenderson/architecture-decision-record
